version: "2"
services:
  app:
    container_name: MDA
    restart: always
    build: .
    ports:
      - "8090:8090"
    volumes: 
      - .:/home/docker/MDA
      - /home/docker/MDA/node_modules
    links:
      - mongoDB
  mongoDB:
    container_name: mongoDB_MDA
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"