# Version: '2'
services:
    web:
        build: .
        depends_on:
            - db
        ports:
            - "8090:8090"
        volumes: 
            - .:/home/docker/MDA
            - /home/docker/MDA/node_modules
    
    db:
        image: mongo
        expose: 
            - "27017"
        volumes: 
            - mongodata:/data/db

volumes: 
    mongodata: